name: docker hub api
"on":
  push:
    branches:
      - main
    paths:
      - "api/**"
      - "models/**"
      - ".github/workflows/hub-api.yml"

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_HUB_USER }}
          password: ${{ secrets.DOCKER_HUB_SECRET }}
      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          push: true
          tags: pierrelf/hempriser:api
          file: api/Dockerfile
          platforms: linux/amd64,linux/arm64
