name: docker hub frontend
"on":
  push:
    branches:
      - main
    paths:
      - 'frontend/**'
jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_HUB_USER }}
          password: ${{ secrets.DOCKER_HUB_SECRET }}
      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          push: true
          tags: pierrelf/hempriser:frontend
          file: frontend/Dockerfile
